version: '3.8'
services:
  web:
    build: .
    container_name: django_app
    restart: always
    working_dir: /app/todo_project
    environment:
      PYTHONPATH: "/app/todo_project"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 todo_project.wsgi:application